version: "3"

services:
  stubby:
    container_name: stubby
    image: carterfields/stubby:armv7
    networks:
      custommacvlan:
        ipv4_address: 192.168.0.253
    expose:
        - "53"
    volumes:
       - '/home/pi/local-docker/pihole/stubby.yml:/usr/local/etc/stubby/stubby.yml'

  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      custommacvlan:
        ipv4_address: 192.168.0.254
    depends_on:
     - stubby
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: 'yourpassword'
      DNS1: 192.168.0.253
      DNS2: "no"
    # Volumes store your data between container upgrades
    volumes:
       - '/home/pi/local-docker/pihole/etc-pihole/:/etc/pihole/'
       - '/home/pi/local-docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  custommacvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"
